### ISSUE TITLE
IDFetcher and resolving fields to prevent over fetching

### ISSUE THREAD

**Issue by F21** [graphql-go/relay#19]
Let's say I have a type called `User`. User has a structure that looks like this:

```graphql
{
  user {
    id
    firstName
    lastName
    birthday {
      month
      day
    }
  }
}
```

In the `NodeDefinitions`, I attempt to return a model to the `IDFetcher`:

```go
IDFetcher: func(id string, info graphql.ResolveInfo) interface{} {

	resolvedID := relay.FromGlobalID(id)

	var resolved interface{}

	if resolvedID.Type == "user" {
		return model.GetUser(resolvedID.ID)
	}

	return resolved
},
```

When fetching the model using `model.GetUser`, how deep should I go and which fields should I return? There are many cases where information for a field is only a different system and require a network call, or a field that is a bit more expensive to retrieve.

While the `graphql.ResolveInfo` object contains the AST and other information, it seems a bit unintuitive to have to use the AST in userland code, especially when we have defined a schema where the fields have separate resolvers so that only the fields requests are resolved.

Has anyone else dealt with this problem? If so, what was your solution?

**Comment by sogko** [comment]
Hi @F21 

Let me try to answer you question:

> how deep should I go and which fields should I return? 

If your `User` struct in Go matches the defined `UserType` schema, `graphql-go` would automatically resolve it for you. In that case, your `model.GetUser()` simply would need to return `*User` that matches your defined schema.

But if you have additional fields, or require a specific way to resolve a field, you would want to implement it by passing a `func(p graphql.ResolveParams)` into `Resolve` params when you defined the `UserType` schema.

If you want to share your graphql schema in a gist, I would be happy to take a look and help you out further.

Cheers!

**Comment by F21** [comment]
@sogko Can you elaborate further?

Here's a gist containing my schema as well as some models (everything's heavily simplified!): https://gist.github.com/F21/bee6a804d724547d83bc

Thanks! :smile:

**Comment by sogko** [comment]
@F21 Awesome, I've taken a look at your gist and I can see why it's overfetching

https://gist.github.com/F21/bee6a804d724547d83bc#file-schema-go-L9
The culprit is in Line 9. It'll run `GetResources()` and evaluate  you can avoid that with a little bit of re-writing your schema.

Here's a quick one that I wrote
https://gist.github.com/sogko/7bf2ef17fad4ed4514b5

Cheers!

**Comment by F21** [comment]
@sogko Thanks for your help! That really helped a lot. There should be an example demonstrating this technique! :smile:

**Comment by sogko** [comment]
@F21 No problem 👍🏻Yeah, documentation is really lacking at the moment, hopefully that can change soon =)
