### ISSUE TITLE
MutationWithClientMutationID retain the mutation name

### ISSUE THREAD

**Issue by bsr203** [graphql-go/relay#7]
Can we retain the Name from `MutationConfig` on the outputted `graphql.FieldConfig` in `MutationWithClientMutationID` function. at

https://github.com/graphql-go/relay/blob/master/mutation.go#L61

so need `Name: config.Name` there.

thanks.

**Comment by sogko** [comment]
Fixed in #9 and #11

Thanks @bsr203  and @piinecone 👍🏻
